### ISSUE TITLE
Zoom applied exponentially after being called several times even with a $.remove()

### ISSUE THREAD

**Issue by reidcooper** [jackmoore/zoom#112]
I have a Marionette function that is called every time a user changes product color. This will enable the zoom of that product color image as well as other locations of that color. In this case, every time I apply a zoom, the zoom applies exponentially. The destroy trigger seems to only destroy the img that it is created once so I tried using $.remove().

```
this.ui.current_image.find('.js-zoomable-image').each(function(){
        var $this = $(this);
        var url = $this.data('large-url');
        $this.find('img.zoomImg').remove();
        $this.zoom({ url: url, touch:touch_val });
      });
```

I figured that every time this function is going to be called, I could remove all the original zooms and then reapply it. However it will start with 2, 4, 6, 12, etc.. 

What am I doing incorrectly?

**Comment by jackmoore** [comment]
Instead of trying to remove zoom yourself, trigger the destroy event.  Try this:

```
this.ui.current_image.find('.js-zoomable-image').each(function(){
        var $this = $(this);
        var url = $this.data('large-url');
        $this.trigger('zoom.destroy');
        $this.zoom({ url: url, touch:touch_val });
      });
```

**Comment by reidcooper** [comment]
I tried that and it will only remove one of those imgs and not multiples.

**Comment by jackmoore** [comment]
Sorry, that was due to a bug (#83).  Made a new release, care to try it again?  

You shouldn't need to be applying zoom to any '.zoomImg' element, since that is the temporary zoomed image created by the zoom plugin.  If you re-assign zoom, it should be to the same element you originally assigned it to.  The code you posted looks fine to me.

**Comment by reidcooper** [comment]
Thanks, Let me give that another shot and see what happens.

**Comment by reidcooper** [comment]
As of right now, your new release has fixed my problem. I was trying to apply zoom on the parent wrapper as required, however I was trying to remove those temp imgs that zoom created within that parent wrapper. I must of misspoke or didn't convey that properly. Thanks for your timely update :)
