### ISSUE TITLE
Could i have a question?

### ISSUE THREAD

**Issue by kkotkkio** [jackmoore/zoom#119]
Frist, I'm sorry that i'm not good english.

Anyway, I want to zoom-in when i other button.

Now, When i coded "zoom({on:'click'})", 
When i click image, is started zoom.

But i have a other button.

I want to image is zoomed when i click other button. 

![2017-02-14 6 14 46](https://cloud.githubusercontent.com/assets/23737489/22922528/7c972942-f2e1-11e6-99d9-7dea6ffd297b.png)

When the zoom-in button, 
1. image will be zoom-in 1 depth.
2. When i mouseover on image, possible to move.

I'm so sorry.. I hope to you understand my english.. 

Have a good day!

**Comment by jackmoore** [comment]
I think you would have to fork the script and make modifications to it to support the behavior you are asking for.  Or find a different script that meets your specific requirements.  Sorry, best of luck.
