### ISSUE TITLE
Control on target image hover

### ISSUE THREAD

**Issue by simonemarin** [jackmoore/zoom#123]
Hallo, is it possible to get the control of the zoom image based on the zoomed image and not in the original image? I am using an overlay covering the whole  page where the zoomed image is rendered but the position control is still based on the original image which lies beneath the zoomed  image.
tx
Simone

**Comment by jackmoore** [comment]
Hi, I understand what you are saying but that's not something I'm going to get into changing.  Would you be able to work around it by putting a relative position and a z-index on the target element so that it sits above your overlay?
