### ISSUE TITLE
Remove overflow:hidden from being added by defauly

### ISSUE THREAD

**Issue by oelbaganwg** [jackmoore/zoom#124]
Hey guys, I love this plugin. Is there anyway to remove the overflow:hidden styles that get automatically added to the container, as I'd like the zoom to break out of the container.

**Comment by jackmoore** [comment]
I've never been asked this before, so I don't think I'll making it into a setting, but feel free to fork and make that change for your use case. Also, I assume you could work around it by doing either of the following:

Override the specificity of the inline style by adding !important to your stylesheet.  For example:
```
.zoom {overflow: auto !important;}
```

Or use jQuery to change the style on the zoom target element:
```
$('.zoom').zoom().css({overflow: auto});
```

**Comment by oelbaganwg** [comment]
Thank you
