### ISSUE TITLE
zoom not working in more than five images, with same class or id  

### ISSUE THREAD

**Issue by sagargc** [jackmoore/zoom#132]
How to fix this issues if i use saveral images more than five, thank you.

**Comment by jackmoore** [comment]
The HTML spec mandates that IDs be unique, so additional elements you've assigned that same ID to are not going to be accessed when you try to use that ID as a DOM query selector. Use a class if you want to access multiple elements using the same selector.

**Comment by sagargc** [comment]
//Still Not Working My Code is here
  <div class="book" id="book" style="background: #fff">                      
             <div class="zoom test">
                 <img src="pages/1.png"/>
             </div>
             <div class="zoom test">
                 <img src="pages/2.png"/>
             </div>
             <div class="zoom test">
                 <img src="pages/3.png"/>
             </div>
             <div class="zoom test">
                 <img src="pages/4.png"/>
             </div>
             <div class="zoom test">
                 <img src="pages/5.png"/>
             </div><div class="page zoom test">
                 <img src="pages/6.png"/>
             </div>
        </div>
        
    // Scripts
   <script>
$(document).ready(function(){
            $('.test').zoom();           
});
</script>

Works till 5th page then last six page wont.
Thank you.

**Comment by jackmoore** [comment]
If you post a link to a live demo I'll have a look, otherwise I think it's going to be hard to diagnose your problem.

**Comment by sagargc** [comment]
link is here 
http://sagarandbrothers.com.np/ebook/test.php
thank you...

**Comment by sagargc** [comment]
if i addred more pages after 5th page, like 6th 7th and so on not working...

**Comment by jackmoore** [comment]
It looks like zoom is working with all the elements it was assigned to.  Here is your markup for the `<img>` elements:

```
<div class="book" id="book" style="background: #fff">                      
     <div class="page zoom">
         <img src="pages/1.png" alt="" />
     </div>
     <div class="page zoom">
         <img src="pages/2.png" alt="" />
     </div>
     <div class="page zoom">
         <img src="pages/3.png" alt="" />
     </div>
     <div class="page zoom">
         <img src="pages/4.png" alt="" />
     </div>
     <div class="page zoom">
         <img src="pages/5.png" alt="" />
     </div>
     <div class="page zoom">
         <img src="pages/5.png" alt="" />
     </div>
</div>
```

So the flipbook feature goes through those defined elements fine, but it continues onto a 6th page which doesn't seem to have corresponding `.page` element in the DOM. I'm not going to go through the code to find where it gets the 6th page from, but it's not the same DOM nodes as zoom was assigned to.  From what I can tell zoom is working correctly for elements that exist at the time it was assigned.

**Comment by sagargc** [comment]
thank you for your kind response.
