### ISSUE TITLE
Touch to zoom on mobiles

### ISSUE THREAD

**Issue by avenicus** [jackmoore/zoom#62]
The zoom works on mobiles and touch event, although there is one slight issue ( minor feature request? ;) which I feel would make it more user friendly. The problem is that the zoom stays "zoomed" even after I've finished touching the mobile. It would be much nicer if the image had zoomed back out to the original state, so that it can be zoomed again easily, while currently it requires two touches to zoom again.

**Comment by rustemgareev** [comment]
Yes, I have the same opinion. Moreover, I wish zoom was optimized for slide events (when you touch device to scroll page) - for example, when my image is 100% device's height, I can't scroll down because any slight touch on image triggers zoom.

**Comment by DrLulz** [comment]
Did you ever find a solution for this?

**Comment by NHuffmanSWX** [comment]
I'm experiencing this, too, on Android 5. Using Chrome. As well as iPhone. Any update on this?

**Comment by NHuffmanSWX** [comment]
Version 1.7.14 but keeping all the top, left, offset.top, offset.left code in $.zoom from 1.7.13 fixes the problem in Android. Still having issues on iPhone.

**Comment by pushkar-deshmukh** [comment]
+1

**Comment by avenicus** [comment]
Version 1.7.15 confirmed fixed & working as expected. Thank you!

**Comment by pirco** [comment]
on that note... a two-finger touch to enable zoom on touch devices would be perfect. google maps implemented that recently.
