### ISSUE TITLE
jsdelivr out of date

### ISSUE THREAD

**Issue by PedroKTFC** [jackmoore/zoom#79]
I notice that the version on jsdelivr is out of date. Just wondering if you had any plans to update?

Much appreciate the plugin btw.

**Comment by jimaek** [comment]
I enabled auto-updates for this project. Now every time a new version is released our bot will automatically add it here http://www.jsdelivr.com/#!jquery.zoom

**Comment by PedroKTFC** [comment]
Thanks.
