### ISSUE TITLE
Zoom not working with modals

### ISSUE THREAD

**Issue by MIACH99** [jackmoore/zoom#96]
Hi, i am using the zoom feature in modal and it is not working. What should i do?

**Comment by sudinem** [comment]
How did you fixed this problem ??

**Comment by MIACH99** [comment]
after modal loads and data rendered i have called the zoom function.
here is the code that  used: 
$(".zoom-load").each(function () {
    $(this).parent().zoom({
        url: $(this).attr('data-zoom-image'),
        target: false,
        touch: false,
        on: 'mouseover',
        magnify: 1
    });
});
<a href="#"><img src="imagethumb.png" alt="image" class="media-object zoom-load" data-zoom-image="fullimage.png"></a>

**Comment by sudinem** [comment]
Thanks. I am using wheelzoom plugin. I think you have posted the code of another plugin. Would you please send me the fully functional code of that.

**Comment by MIACH99** [comment]
sorry, but i haven't used the wheelzoom plugin.
